### ISSUE TITLE
Translation into other languages?

### ISSUE THREAD

**Issue by thopanX** [danpros/htmly-docs#1]
Is it possible and if yes, how to set it up?

**Comment by danpros** [comment]
Wait, I will create new repo. What lang is it? later we can use folder on the site, eg. `docs.htmly.com/de`

**Comment by thopanX** [comment]
German, so "de"

**Comment by danpros** [comment]
Done creating the repo https://github.com/danpros/htmly-docs-de

It will sync once an hour. Do I need to upload existing docs into it?

**Comment by thopanX** [comment]
Thanks. If you could upload existing stuff once, I'd be grateful.

Am 5. Juni 2024 14:10:04 MESZ schrieb Dan ***@***.***>:

**Comment by danpros** [comment]
OK its done https://github.com/danpros/htmly-docs-de
